{% set name = "eslint" %}
{% set version = "8.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eslint/eslint/archive/refs/tags/v{{ version }}.tar.gz
  sha256: cb42acc3d65941af238769c40dbb50ece95c27e97e01bc61ad30233b57a26655

build:
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - yarn
  run:
    - nodejs

test:
  commands:
    - eslint --help

about:
  home: https://github.com/eslint/eslint
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Find and fix problems in your JavaScript code.

extra:
  recipe-maintainers:
    - xhochy
