{% set name = "eslint" %}
{% set version = "8.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eslint/eslint/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ee8d122e93391e59d7a0aaa4f52b203eece8ed8cb8fb44e833f7e6ec16fc10e3

build:
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - yarn
  run:
    - nodejs

test:
  commands:
    - eslint --help

about:
  home: https://github.com/eslint/eslint
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Find and fix problems in your JavaScript code.

extra:
  recipe-maintainers:
    - xhochy
