{% set name = "eslint" %}
{% set version = "9.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eslint/eslint/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0f2bf837da4c846518d2a109caa94a6cb406ac6ab0b9620e49fd8b473f5ac306

build:
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - yarn <2
  run:
    - nodejs

test:
  commands:
    - eslint --help

about:
  home: https://github.com/eslint/eslint
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Find and fix problems in your JavaScript code.

extra:
  recipe-maintainers:
    - xhochy
