{% set name = "eslint" %}
{% set version = "8.37.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eslint/eslint/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 63f9c5266beab3d286d33f84730bdf5bc0f4203308a8a306df7b6860180eaba6

build:
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - yarn <2
  run:
    - nodejs

test:
  commands:
    - eslint --help

about:
  home: https://github.com/eslint/eslint
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Find and fix problems in your JavaScript code.

extra:
  recipe-maintainers:
    - xhochy
