{% set name = "eslint" %}
{% set version = "8.30.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eslint/eslint/archive/refs/tags/v{{ version }}.tar.gz
  sha256: da7eb4cf860e243b8fed402d308d3c2d158e306ab9f9775daa1b83f1c6cd83c5

build:
  number: 0

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - yarn
  run:
    - nodejs

test:
  commands:
    - eslint --help

about:
  home: https://github.com/eslint/eslint
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Find and fix problems in your JavaScript code.

extra:
  recipe-maintainers:
    - xhochy
