schema_version: 1

context:
  version: "10.1.0"

package:
  name: eslint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/eslint/-/eslint-${{ version }}.tgz
  sha256: a5a3fea5cb42fbd9ffab6aa7b55c0ba3c462d3c3831fbcafa27378537f68c492

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - eslint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Find and fix problems in your JavaScript code.
  homepage: https://github.com/eslint/eslint

extra:
  recipe-maintainers:
    - danielnachun
    - xhochy
