schema_version: 1

context:
  version: "10.0.1"

package:
  name: eslint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/eslint/-/eslint-${{ version }}.tgz
  sha256: cb26aa15fde37fa286e813e0843f261996dfd831c2cccdca18c6ddad11163c74

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - eslint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Find and fix problems in your JavaScript code.
  homepage: https://github.com/eslint/eslint

extra:
  recipe-maintainers:
    - danielnachun
    - xhochy
