schema_version: 1

context:
  version: "10.0.3"

package:
  name: eslint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/eslint/-/eslint-${{ version }}.tgz
  sha256: 59441825ea6441f1c71eea0b4caf0699bc2c6a3ea861c4996b2833e025095f4e

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - eslint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Find and fix problems in your JavaScript code.
  homepage: https://github.com/eslint/eslint

extra:
  recipe-maintainers:
    - danielnachun
    - xhochy
