schema_version: 1

context:
  version: "10.0.2"

package:
  name: eslint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/eslint/-/eslint-${{ version }}.tgz
  sha256: 2fb6e44a35b25dee20c643619729521d1b8b25977b968aaf3aa137b75dc4fc86

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - eslint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Find and fix problems in your JavaScript code.
  homepage: https://github.com/eslint/eslint

extra:
  recipe-maintainers:
    - danielnachun
    - xhochy
