schema_version: 1

context:
  version: "10.8.0"

package:
  name: eslint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/eslint/-/eslint-${{ version }}.tgz
  sha256: d17fc2ba1f036a4c6c448d3ae1893a163f29c064a33984b11520c3992e9a66b2

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - eslint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Find and fix problems in your JavaScript code.
  homepage: https://github.com/eslint/eslint

extra:
  recipe-maintainers:
    - danielnachun
    - xhochy
